/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project.pbo;

import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aqila fadia
 */
public class JavaPOS extends javax.swing.JFrame {

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CarammelLatte = new javax.swing.JButton();
        jButtonKopiVietnam = new javax.swing.JButton();
        HotMatcha = new javax.swing.JButton();
        HazelNut = new javax.swing.JButton();
        Cappucino = new javax.swing.JButton();
        ChocolateBanana = new javax.swing.JButton();
        CoffeItaly = new javax.swing.JButton();
        TehTarik = new javax.swing.JButton();
        FloatCoffe = new javax.swing.JButton();
        IceCreamGellato = new javax.swing.JButton();
        MilkCoffe = new javax.swing.JButton();
        IceCreamOreo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtnc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jbtnPay = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPembayaran = new javax.swing.JComboBox<>();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CarammelLatte.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CarammelLatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/3.png"))); // NOI18N
        CarammelLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarammelLatteActionPerformed(evt);
            }
        });
        jPanel1.add(CarammelLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 100, 100));

        jButtonKopiVietnam.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonKopiVietnam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1.png"))); // NOI18N
        jButtonKopiVietnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKopiVietnamActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKopiVietnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 100));

        HotMatcha.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        HotMatcha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/2.png"))); // NOI18N
        HotMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotMatchaActionPerformed(evt);
            }
        });
        jPanel1.add(HotMatcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, 100));

        HazelNut.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        HazelNut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/4.png"))); // NOI18N
        HazelNut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HazelNutActionPerformed(evt);
            }
        });
        jPanel1.add(HazelNut, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 100, 100));

        Cappucino.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Cappucino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/5.png"))); // NOI18N
        Cappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CappucinoActionPerformed(evt);
            }
        });
        jPanel1.add(Cappucino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 100));

        ChocolateBanana.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ChocolateBanana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/6.png"))); // NOI18N
        ChocolateBanana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocolateBananaActionPerformed(evt);
            }
        });
        jPanel1.add(ChocolateBanana, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, 100));

        CoffeItaly.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CoffeItaly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/7.png"))); // NOI18N
        CoffeItaly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoffeItalyActionPerformed(evt);
            }
        });
        jPanel1.add(CoffeItaly, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 100, 100));

        TehTarik.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TehTarik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/8.png"))); // NOI18N
        TehTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TehTarikActionPerformed(evt);
            }
        });
        jPanel1.add(TehTarik, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 100, 100));

        FloatCoffe.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        FloatCoffe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/10.png"))); // NOI18N
        FloatCoffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FloatCoffeActionPerformed(evt);
            }
        });
        jPanel1.add(FloatCoffe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 100, 100));

        IceCreamGellato.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        IceCreamGellato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/11.png"))); // NOI18N
        IceCreamGellato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IceCreamGellatoActionPerformed(evt);
            }
        });
        jPanel1.add(IceCreamGellato, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 100, 100));

        MilkCoffe.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        MilkCoffe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/9.png"))); // NOI18N
        MilkCoffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkCoffeActionPerformed(evt);
            }
        });
        jPanel1.add(MilkCoffe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, 100));

        IceCreamOreo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        IceCreamOreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/12.png"))); // NOI18N
        IceCreamOreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IceCreamOreoActionPerformed(evt);
            }
        });
        jPanel1.add(IceCreamOreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 100, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 530, 390));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 80));

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 90, 80));

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 80));

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 80));

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 80));

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 90, 80));

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, 80));

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 90, 80));

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 90, 80));

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, 80));

        jbtnDot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 90, 80));

        jbtnc.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnc.setText("C");
        jbtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 90, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 390));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barang", "Kuantitas", "Jumlah"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 350, 320));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Pajak");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 150, -1));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel3.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 150, -1));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel3.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 150, -1));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 130));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPay.setText("Bayar");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        jbtnExit.setBackground(new java.awt.Color(255, 0, 51));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(255, 255, 255));
        jbtnExit.setText("Keluar");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 350, 40));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 40));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 150, -1));

        jbtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnRemove.setText("Hapus");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 150, 40));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 400, 130));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Metode Pembayaran");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Kembali");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Tunai");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel7.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 140, -1));

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel7.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 140, -1));

        jcboPembayaran.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jcboPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunai", "Transfer", " " }));
        jcboPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPembayaranActionPerformed(evt);
            }
        });
        jPanel7.add(jcboPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 120, -1));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 390, 130));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 1230, 170));

        jtxtBarCode.setFont(new java.awt.Font("C39HrP24DhTt", 0, 48)); // NOI18N
        jtxtBarCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 350, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//==============================================Function=================================
    public void ItemCost()
    {
        double sum = 0;
        
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        
        double cTax = (cTotal1 * 3.9)/100;
        String iTaxTotal = String.format("Rp %.3f", cTax);
        jtxtTax.setText(iTaxTotal);
        
        String iSubTotal = String.format("Rp %.3f", cTotal1);
        jtxtSubTotal.setText(iSubTotal);
        
         String iTotal = String.format("Rp %.3f", cTotal1 + cTax);
        jtxtTotal.setText(iTotal);
        
         String BarCode = String.format("Total Rp %.3f", cTotal1 + cTax);
        jtxtBarCode.setText(BarCode);
    }
    
    //==============================================Function=================================
    public void Change()
    {
        double sum =0;
        double tax =3.9;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        double cTax = (sum * 3.9)/100;
        double cChange = (cash - (sum + cTax));
        
        String ChangeGiven = String.format("Rp %.3f", cChange);
        jtxtChange.setText(ChangeGiven);
    }
    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
       String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn9.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn9.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn7.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn7.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
       String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn8.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn8.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
       String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn4.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn4.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn5.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn5.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn6.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn6.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
       String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn1.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn1.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn3.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn3.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
       String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn2.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn2.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
            jtxtDisplay.setText(jbtn0.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + jbtn0.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        if(! jtxtDisplay.getText().contains("."))
        {
            jtxtDisplay.setText(jtxtDisplay.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncActionPerformed
    jtxtDisplay.setText("");
    jtxtChange.setText("");
    }//GEN-LAST:event_jbtncActionPerformed

    private void CarammelLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarammelLatteActionPerformed
        double PriceOfItem = 32.000;
        String formattedPrice = String.format("%.3f", PriceOfItem);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Carammel Latte", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_CarammelLatteActionPerformed

    private void jButtonKopiVietnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKopiVietnamActionPerformed
        double PriceOfItem = 28.000;
        String formattedPrice = String.format("%.3f", PriceOfItem);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Kopi Vietnam", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_jButtonKopiVietnamActionPerformed

    private void HotMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotMatchaActionPerformed
        double PriceOfItem = 23.000;
        String formattedPrice = String.format("%.3f", PriceOfItem);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hot Matcha", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_HotMatchaActionPerformed

    private void HazelNutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HazelNutActionPerformed
       double PriceOfItem = 20.000;
       String formattedPrice = String.format("%.3f", PriceOfItem);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hazel Nut", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_HazelNutActionPerformed

    private void CappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CappucinoActionPerformed
        double PriceOfItem = 22.000;
        String formattedPrice = String.format("%.3f", PriceOfItem);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cappucino", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_CappucinoActionPerformed

    private void ChocolateBananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocolateBananaActionPerformed
        double PriceOfItem = 26.000;
        String formattedPrice = String.format("%.3f", PriceOfItem);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chocolate Banana", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_ChocolateBananaActionPerformed

    private void CoffeItalyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoffeItalyActionPerformed
       double PriceOfItem = 35.000;
       String formattedPrice = String.format("%.3f", PriceOfItem);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Coffe Italy", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_CoffeItalyActionPerformed

    private void TehTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TehTarikActionPerformed
        double PriceOfItem = 17.000;
        String formattedPrice = String.format("%.3f", PriceOfItem);
        
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Teh Tarik", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_TehTarikActionPerformed

    private void FloatCoffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FloatCoffeActionPerformed
        double PriceOfItem = 25.000;
        String formattedPrice = String.format("%.3f", PriceOfItem);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Float Coffe", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_FloatCoffeActionPerformed

    private void IceCreamGellatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IceCreamGellatoActionPerformed
        double PriceOfItem = 30.000;
        String formattedPrice = String.format("%.3f", PriceOfItem);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Cream Gellato", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_IceCreamGellatoActionPerformed

    private void MilkCoffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkCoffeActionPerformed
        double PriceOfItem = 20.000;
        String formattedPrice = String.format("%.3f", PriceOfItem);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Milk Coffe", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_MilkCoffeActionPerformed

    private void IceCreamOreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IceCreamOreoActionPerformed
        double PriceOfItem = 34.000;
        String formattedPrice = String.format("%.3f", PriceOfItem);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Ice Cream Oreo", "1", formattedPrice});
        ItemCost();
    }//GEN-LAST:event_IceCreamOreoActionPerformed

    private void jtxtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarCodeActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Example Coffee Makassar");
        MessageFormat footer = new MessageFormat("Halaman {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL, header,footer);  
        }
        
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("Tidak ada Printer yang ditemukan", e.getMessage());
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
       int RemoveItem = jTable1.getSelectedRow();
       if( RemoveItem >= 0)
       {
           model.removeRow(RemoveItem);
       }
       
       ItemCost();
       
        if (jcboPembayaran.getSelectedItem().equals("Tunai"))
       {
           Change();
       }
       else
       {
            jtxtChange.setText("");
            jtxtDisplay.setText("");
       }
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
       if (jcboPembayaran.getSelectedItem().equals("Tunai"))
            {
                Change();
            }
            else
            {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
            }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
        jtxtTotal.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jcboPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPembayaranActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       
        frame = new JFrame("Keluar");
        Object[] options = {"Ya", "Tidak"};
        int n = JOptionPane.showOptionDialog(frame,
            "Konfirmasi jika Anda ingin keluar",
            "Point of Sale",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]);

        if (n == JOptionPane.YES_OPTION) {
            System.exit(0);
       }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cappucino;
    private javax.swing.JButton CarammelLatte;
    private javax.swing.JButton ChocolateBanana;
    private javax.swing.JButton CoffeItaly;
    private javax.swing.JButton FloatCoffe;
    private javax.swing.JButton HazelNut;
    private javax.swing.JButton HotMatcha;
    private javax.swing.JButton IceCreamGellato;
    private javax.swing.JButton IceCreamOreo;
    private javax.swing.JButton MilkCoffe;
    private javax.swing.JButton TehTarik;
    private javax.swing.JButton jButtonKopiVietnam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnc;
    private javax.swing.JComboBox<String> jcboPembayaran;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
